version: 0.0
os: linux
files:
hooks:
  BeforeInstall:
    - location: scripts/pull_docker_image.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_docker_image.sh
      timeout: 300
      runas: root
