# Use the SDK image for building and development
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY ["IPMS.API/IPMS.API.csproj", "IPMS.API/"]
RUN dotnet restore "IPMS.API/IPMS.API.csproj"

# Copy everything else and build the app
COPY . .
WORKDIR "/src/IPMS.API"
EXPOSE 80

# Build the application
RUN dotnet build "IPMS.API.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "IPMS.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Use the runtime image for the final stage
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
EXPOSE 80

# Copy the published app to the final runtime image
COPY --from=publish /app/publish .

# Set environment variable to run in development mode
ENV ASPNETCORE_ENVIRONMENT=Development

# Run the application
ENTRYPOINT ["dotnet", "IPMS.API.dll"]
