// <auto-generated />
using System;
using IPMS.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IPMS.DataAccess.Migrations
{
    [DbContext(typeof(IPMSDbContext))]
    [Migration("20240526170007_AddBorrowIoTField_ChangeClassOfStudentNotNull")]
    partial class AddBorrowIoTField_ChangeClassOfStudentNotNull
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IPMS.DataAccess.Models.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)");

                    b.Property<Guid?>("SyllabusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Assessment", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.ClassTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("TopicId");

                    b.ToTable("ClassTopic", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Committee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("LecturerId");

                    b.ToTable("Committee", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.ComponentsMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<int>("MasterType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentsMaster", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.IoTComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("IoTComponent", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.IPMSClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BorrowIoTComponentDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ChangeGroupDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ChangeTopicDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateGroupDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SemesterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("IPMSClass", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.IPMSUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.LecturerGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommitteeId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("LecturerGrade", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.MemberHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMemberSwapApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProjectFromApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProjectToApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MemberSwapId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectFromComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectFromId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectToComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MemberHistory", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.ProjectSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FinalGrade")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmissionLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubmissionModuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubmissionModuleId");

                    b.ToTable("ProjectSubmission", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileLink")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReportTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportTypeId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.ReportType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ReportType", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SyllabusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId");

                    b.ToTable("Semester", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ContributePercentage")
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)");

                    b.Property<decimal?>("FinalGrade")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<Guid?>("InformationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("InformationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.SubmissionModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)");

                    b.Property<Guid?>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("LectureId");

                    b.HasIndex("SemesterId");

                    b.ToTable("SubmissionModule", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Syllabus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Syllabus", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.TopicFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FavoriteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteId");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicFavorite", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Assessment", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.Syllabus", "Syllabus")
                        .WithMany("Assessments")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.ClassTopic", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IPMSClass", "Class")
                        .WithMany("Topics")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IPMS.DataAccess.Models.Project", "Project")
                        .WithOne("Topic")
                        .HasForeignKey("IPMS.DataAccess.Models.ClassTopic", "ProjectId");

                    b.HasOne("IPMS.DataAccess.Models.Topic", "Topic")
                        .WithMany("Classes")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Class");

                    b.Navigation("Project");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Committee", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IPMSClass", "Class")
                        .WithMany("Committees")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", "Lecturer")
                        .WithMany("Committees")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Class");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.ComponentsMaster", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IoTComponent", "Component")
                        .WithMany("ComponentsMasters")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Component");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Favorite", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", "Lecturer")
                        .WithMany("Favorites")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.IPMSClass", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.Semester", "Semester")
                        .WithMany("Classes")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.LecturerGrade", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.Committee", "Committee")
                        .WithMany("Grades")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IPMS.DataAccess.Models.ProjectSubmission", "Submission")
                        .WithMany("Grades")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Committee");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Project", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", "Owner")
                        .WithMany("OwnProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.ProjectSubmission", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.Project", "Project")
                        .WithMany("Submissions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IPMS.DataAccess.Models.SubmissionModule", "SubmissionModule")
                        .WithMany("ProjectSubmissions")
                        .HasForeignKey("SubmissionModuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");

                    b.Navigation("SubmissionModule");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Report", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.ReportType", "ReportType")
                        .WithMany("Reports")
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReportType");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Semester", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.Syllabus", "Syllabus")
                        .WithMany("Semesters")
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Syllabus");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Student", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IPMSClass", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", "Information")
                        .WithMany("Students")
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IPMS.DataAccess.Models.Project", "Project")
                        .WithMany("Students")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Class");

                    b.Navigation("Information");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.SubmissionModule", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.Assessment", "Assessment")
                        .WithMany("Modules")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", "Lecturer")
                        .WithMany("Modules")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IPMS.DataAccess.Models.Semester", "Semester")
                        .WithMany("Modules")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Assessment");

                    b.Navigation("Lecturer");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Topic", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", "Owner")
                        .WithMany("OwnTopics")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.TopicFavorite", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.Favorite", "Favorite")
                        .WithMany("Topics")
                        .HasForeignKey("FavoriteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IPMS.DataAccess.Models.Topic", "Topic")
                        .WithMany("Favorites")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Favorite");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("IPMS.DataAccess.Models.IPMSUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Assessment", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Committee", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Favorite", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.IoTComponent", b =>
                {
                    b.Navigation("ComponentsMasters");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.IPMSClass", b =>
                {
                    b.Navigation("Committees");

                    b.Navigation("Students");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.IPMSUser", b =>
                {
                    b.Navigation("Committees");

                    b.Navigation("Favorites");

                    b.Navigation("Modules");

                    b.Navigation("OwnProjects");

                    b.Navigation("OwnTopics");

                    b.Navigation("Reports");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Project", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Submissions");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.ProjectSubmission", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.ReportType", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Semester", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.SubmissionModule", b =>
                {
                    b.Navigation("ProjectSubmissions");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Syllabus", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("IPMS.DataAccess.Models.Topic", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
